#!/usr/bin/env bash

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

# Install zsh
echo 'Install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

echo 'Install zsh-autosuggestions'
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# Add global gitignore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile $HOME/.global-gitignore

#########################################################
### Setup Symlinks
#########################################################
# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

# Symlink yarn prefs
rm $HOME/.yarnrc
ln -s $HOME/.dotfiles/shell/.yarnrc $HOME/.yarnrc

#########################################################
### Setup composer, brew and mas-cli
#########################################################

echo 'Install homebrew...'
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo 'Install composer'
brew install composer

echo 'Install mas'
brew install mas

#########################################################
### Install common dev/shell tools
#########################################################
echo "Installing ZSH syntax highlighting"
brew install zsh-syntax-hightlighting

echo 'Install z...'
brew install z

echo 'Install wget...'
brew install wget

echo 'Install httpie...'
brew install httpie

echo 'Install hub...'
brew install hub

# Docker (not needed yet)
# echo 'Install docker...'
# brew cask install docker
# brew install docker-compose

#########################################################
### Install PHP (not needed yet)
#########################################################
# echo 'Add henkrehorst/php tap...'
# brew tap henkrehorst/php

# echo 'Install PHP 7.2...'
# brew install valet-php@7.2
# brew link valet-php@7.2 --force

# echo 'Install imagemagick...'
# brew install imagemagick

# echo 'Install imagick...'
# pecl install imagick

# echo 'Install Prestissimo for Composer...'
# composer global require hirak/prestissimo

#########################################################
### Install NodeJS
#########################################################
echo 'Install node...'
brew install node

echo 'Install yarn...'
brew install yarn

echo 'Install fnm...'
brew install Schniz/tap/fnm
eval "$(fnm env --multi)"
fnm install 10
fnm install 12
fnm install 14
fnm default 12

#########################################################
### Install GUI tools and software
#########################################################
echo 'Install Google Chrome...'
brew cask install google-chrome

echo 'Install iterm2...'
brew cask install iterm2

echo 'Install 1Password...'
brew cask install 1password

echo 'Install Spotify...'
brew cask install spotify

# echo 'Install numi...'
# brew cask install numi

# echo 'Install TablePlus'
# brew cask install tableplus

echo 'Install Visual Studio Code'
brew cask install visual-studio-code

# echo 'Install Cleanshot X'
# brew cask install cleanshot

echo 'Install Gifox'
brew cask install gifox

# echo 'Install Magnet...'
# mas install 441258766

echo 'Install The Unarchiver...'
mas install 425424353

echo 'Install Xcode...'
mas install 497799835

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'All done!'
echo 'Things to do to make the powerlevel10k terminal theme work:'
echo '1. Install fonts included in ~/.dotfiles/misc'
echo '2. Install theme included in ~/.dotfiles/misc'

echo '++++++++++++++++++++++++++++++'
echo 'Some optional tidbits'

echo "1. Set some sensible MacOS defaults by running: $HOME/.dotfiles/macos/set-defaults.sh"
echo "2. Make a .dotfiles-custom/shell/.aliases for your personal commands"

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
